---
title: "vodafone-analysis"
author: "ahmed-akram"
date: "May 23, 2016"
output: html_document
---

```{r, message=FALSE, comment=NA}

library(plyr)
library(e1071)
library(rpart)
library(randomForest)
library(neuralnet)
library(dplyr)
library(ipred)
library(ggplot2)

set.seed(10)


model_train <- read.csv("data/train.csv")
model_test <- read.csv("data/test.csv")
```

renaming columns

```{r}
model_train <- model_train %>% rename(
    MONTH1_USAGE = X206_USAGE,
    MONTH2_USAGE = X207_USAGE,
    MONTH3_USAGE = X208_USAGE,
    MONTH4_USAGE = X209_USAGE,
    MONTH5_USAGE = X210_USAGE,
    MONTH1_SESSIONS = X206_SESSION_COUNT,
    MONTH2_SESSIONS = X207_SESSION_COUNT,
    MONTH3_SESSIONS = X208_SESSION_COUNT,
    MONTH4_SESSIONS = X209_SESSION_COUNT,
    MONTH5_SESSIONS = X210_SESSION_COUNT
)

model_test <- model_test %>% rename(
    MONTH1_USAGE = X206_USAGE,
    MONTH2_USAGE = X207_USAGE,
    MONTH3_USAGE = X208_USAGE,
    MONTH4_USAGE = X209_USAGE,
    MONTH5_USAGE = X210_USAGE,
    MONTH1_SESSIONS = X206_SESSION_COUNT,
    MONTH2_SESSIONS = X207_SESSION_COUNT,
    MONTH3_SESSIONS = X208_SESSION_COUNT,
    MONTH4_SESSIONS = X209_SESSION_COUNT,
    MONTH5_SESSIONS = X210_SESSION_COUNT
)
```

adding the total usage, total sessions and avg usage per session
```{r}
add_totals <- function(data) {
	data$TOTAL_USAGE <- data %>% apply(1, function(row) {
	return(row[['MONTH1_USAGE']] + row[['MONTH2_USAGE']] + row[['MONTH3_USAGE']] + row[['MONTH4_USAGE']] + row[['MONTH5_USAGE']])
})	
	
	data$TOTAL_SESSIONS <- data %>% apply(1, function(row) {
	return(row[['MONTH1_SESSIONS']] + row[['MONTH2_SESSIONS']] + row[['MONTH3_SESSIONS']] + row[['MONTH4_SESSIONS']] + row[['MONTH5_SESSIONS']])
})
	
	data$AVG_PER_SESSION <- data %>% apply(1, function(row) {
	return(row[['TOTAL_USAGE']] / row[['TOTAL_SESSIONS']])
})
	
	data
}

model_train <- add_totals(model_train)
model_test <- add_totals(model_test)
```


plotting the TOTAL USAGE against the TOTAL SESSIONS (taking a subset of the data to remove the extreme outliers)
```{r}
model_train %>% subset(TOTAL_USAGE < 100000) %>% subset(TOTAL_SESSIONS < 20000) %>% ggplot(aes(x=TOTAL_SESSIONS, y=TOTAL_USAGE)) + geom_point(aes(color=factor(TARGET))) +
scale_color_manual("Target\n",labels = c("0", "1"), values = c("#EFADA9", "#69B5C7")) +
	theme(axis.title.y = element_text(size=12,angle=0,hjust=0.5,vjust=1,lineheight=40))
```


Average per session vs. Total sessions
```{r}
model_train %>% subset(TOTAL_SESSIONS < 10000) %>% subset(AVG_PER_SESSION < 500) %>% ggplot(aes(x=TOTAL_SESSIONS, y=AVG_PER_SESSION)) + geom_point(aes(color=factor(TARGET))) +
scale_color_manual("Target\n",labels = c("0", "1"), values = c("#EFADA9", "#69B5C7")) +
	theme(axis.title.y = element_text(size=12,angle=0,hjust=0.5,vjust=1,lineheight=40))
```


Total usage density:
```{r}
model_train %>% subset(TOTAL_USAGE < 50000) %>% 
	ggplot(aes(TOTAL_USAGE, fill=factor(TARGET))) +
	scale_fill_manual("Target\n",labels = c("0", "1"), values = c("#EFADA9", "#69B5C7")) +
    geom_density(alpha=I(0.7)) +
	theme(axis.title.y = element_text(size=12,angle=0,hjust=0.5,vjust=1,lineheight=40)) + 
	labs(x="Total usage for 5 months", y="density")
	
```


Average per session density:
```{r}
model_train %>% subset(AVG_PER_SESSION < 25) %>% 
	ggplot(aes(AVG_PER_SESSION, fill=factor(TARGET))) +
	scale_fill_manual("Target\n",labels = c("0", "1"), values = c("#EFADA9", "#69B5C7")) +
    geom_density(alpha=I(0.7)) +
	theme(axis.title.y = element_text(size=12,angle=0,hjust=0.5,vjust=1,lineheight=40)) + 
	labs(x="Average Usage Per Session", y="density")
	
```


Weighted average vs. Average usage:
```{r}
model_train %>% mutate(WEIGHTED_AVG = (5*MONTH5_USAGE + 4*MONTH4_USAGE + 3*MONTH3_USAGE + 2*MONTH2_USAGE + MONTH1_USAGE) / 15)

model_train %>% subset(MEAN_USAGE < 15000) %>% ggplot(aes(x=MEAN_USAGE, y=WEIGHTED_AVG)) + geom_point(aes(color=factor(TARGET))) +
scale_color_manual("Target\n",labels = c("0", "1"), values = c("#EFADA9", "#69B5C7")) +
	theme(axis.title.y = element_text(size=12,angle=0,hjust=0.5,vjust=1,lineheight=40)) + scale_x_continuous(breaks = round(seq(min(model_train$MEAN_USAGE), max(model_train$MEAN_USAGE), by = 1000),1)) +
  scale_y_continuous(breaks = round(seq(min(model_train$WEIGHTED_AVG), max(model_train$WEIGHTED_AVG), by = 1000),1))
```

